import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { addressForTarget, addressFromParts, addressPartsForDraft, appendForwardingAddressHistory, forwardingAddressHistoryForTarget, forwardingAddressPlaceholder, normalizeTargetBasePath, targetFromDraft } from "../../src/renderer/components/ConfigPages";
import { getAppConfigValidationError } from "../../src/shared/validation";
import { ConfigStore } from "../../src/core/config/config-store";

test("does not emit an empty base path for root addresses", () => {
  assert.equal(normalizeTargetBasePath("/"), undefined);
  assert.equal(normalizeTargetBasePath("//"), undefined);
});

test("keeps a real target base path after trimming trailing slashes", () => {
  assert.equal(normalizeTargetBasePath("/ant///"), "/ant");
});

test("produces a saveable target for a root address", () => {
  const target = targetFromDraft({ id: "hq", name: "hq", address: "http://127.0.0.1:7778/", enabled: true }, 0);
  assert.equal(target.basePath, undefined);
  assert.equal(getAppConfigValidationError({
    server: { bindHost: "127.0.0.1", port: 8080, timeoutMs: 30000, loggingEnabled: true },
    httpRules: [],
    tcpTargets: [target],
    localValues: {},
    mapValues: {},
    accounts: {},
    cache: { rootDir: "", downloadTarget: "", decryptEnabled: false, autoDownload: false },
  }), undefined);
});

test("defaults a bare legacy-style reqxml address to TCP", () => {
  const target = targetFromDraft({ id: "jy", name: "jy", address: "123.103.83.82:6110", enabled: true }, 1);
  assert.equal(target.protocol, undefined);
  assert.equal(target.transport, undefined);
});

test("splits forwarding addresses into host and port while preserving protocol and path", () => {
  assert.deepEqual(addressPartsForDraft("tcp://123.103.83.82:6110"), { host: "123.103.83.82", port: "6110" });
  assert.deepEqual(addressPartsForDraft("http://127.0.0.1:8080/ant"), { host: "127.0.0.1", port: "8080" });
  assert.deepEqual(addressPartsForDraft(":6110"), { host: "", port: "6110" });
  assert.equal(addressFromParts("http://127.0.0.1:8080/ant", "10.0.0.2", "9090"), "http://10.0.0.2:9090/ant");
  assert.equal(addressFromParts("123.103.83.82:6110", "123.103.83.83", "6111"), "123.103.83.83:6111");
  assert.equal(addressFromParts("123.103.83.82:6110", "", "6110"), ":6110");
});

test("accepts a complete HTTPS forwarding URL without an explicit port", () => {
  const target = targetFromDraft({ id: "hq", name: "hq", address: "https://h5khtest.citics.com/ant", enabled: true }, 0);
  assert.equal(target.host, "h5khtest.citics.com");
  assert.equal(target.port, 443);
  assert.equal(target.protocol, "https");
  assert.equal(target.transport, "http");
  assert.equal(target.basePath, "/ant");
});

test("does not display a TCP target as HTTP when legacy protocol metadata is present", () => {
  assert.equal(addressForTarget({ id: "jy", name: "jy", host: "123.103.83.82", port: 6064, protocol: "http", enabled: true }), "tcp://123.103.83.82:6064");
  assert.equal(addressForTarget({ id: "jy", name: "jy", host: "123.103.83.82", port: 6064, protocol: "http", transport: "http", enabled: true }), "http://123.103.83.82:6064");
});

test("saves and reloads the forwarding target generated by the address form", async () => {
  const directory = await mkdtemp(path.join(os.tmpdir(), "local-forwarder-address-save-"));
  const target = targetFromDraft({ id: "hq", name: "hq", address: "http://127.0.0.1:7778//", enabled: true }, 0);
  const config = {
    server: { bindHost: "127.0.0.1", port: 8080, timeoutMs: 30000, loggingEnabled: true },
    httpRules: [],
    tcpTargets: [target],
    localValues: {},
    mapValues: {},
    accounts: {},
    cache: { rootDir: "", downloadTarget: "", decryptEnabled: false, autoDownload: false },
  };
  try {
    const store = new ConfigStore(path.join(directory, "internal.json"));
    await store.save(config);
    const restored = await store.load();
    assert.deepEqual(restored.tcpTargets, [target]);
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
});

test("address fields auto-save on blur without the explanatory text or save button", async () => {
  const [source, runtimeSource] = await Promise.all([
    readFile("src/renderer/components/ConfigPages.tsx", "utf8"),
    readFile("src/renderer/components/RuntimePanel.tsx", "utf8"),
  ]);
  assert.doesNotMatch(source, /按 hq、jy、zx 顺序配置旧版 Node 转发地址/);
  assert.doesNotMatch(source, /保存转发地址/);
  assert.match(source, /saveAddressDrafts/);
  assert.match(source, /onBlur=\{\(\) => void saveAddressDrafts\(\)\}/);
  assert.match(source, /address-input/);
  assert.doesNotMatch(source, /address-port-input/);
  assert.match(source, /value=\{draft\.address\}/);
  assert.doesNotMatch(runtimeSource, /监听地址/);
});

test("uses target-specific examples when forwarding address inputs are empty", async () => {
  assert.equal(forwardingAddressPlaceholder(0), "60.12.9.58:7778");
  assert.equal(forwardingAddressPlaceholder(1), "123.103.83.82:6064");
  assert.equal(forwardingAddressPlaceholder(2), "123.103.83.82:6064");

  const source = await readFile("src/renderer/components/ConfigPages.tsx", "utf8");
  assert.match(source, /placeholder=\{forwardingAddressPlaceholder\(index\)\}/);
  assert.doesNotMatch(source, /value=\{forwardingAddressPlaceholder\(index\)\}/);
});

test("keeps recent forwarding addresses unique and newest first", () => {
  assert.deepEqual(
    appendForwardingAddressHistory(["10.0.0.12:7776", "123.103.83.82:7776"], " 123.103.83.82:7776 "),
    ["123.103.83.82:7776", "10.0.0.12:7776"],
  );
});

test("limits forwarding address history to the ten most recent entries", () => {
  const history = Array.from({ length: 10 }, (_, index) => `10.0.0.${index}:7776`);
  assert.deepEqual(appendForwardingAddressHistory(history, "10.0.0.99:7776"), ["10.0.0.99:7776", ...history.slice(0, 9)]);
});

test("keeps market, trading, and news forwarding histories separate", () => {
  const history = { hq: ["hq.example:7776"], jy: ["jy.example:7776"], zx: ["zx.example:7776"] };
  assert.deepEqual(forwardingAddressHistoryForTarget(history, "hq"), ["hq.example:7776"]);
  assert.deepEqual(forwardingAddressHistoryForTarget(history, "jy"), ["jy.example:7776"]);
  assert.deepEqual(forwardingAddressHistoryForTarget(history, "zx"), ["zx.example:7776"]);
  assert.deepEqual(forwardingAddressHistoryForTarget(["legacy.example:7776"], "hq"), []);
});

test("renders an arrow toggle and history select for forwarding addresses", async () => {
  const [source, styleSource] = await Promise.all([
    readFile("src/renderer/components/ConfigPages.tsx", "utf8"),
    readFile("src/renderer/styles.css", "utf8"),
  ]);
  assert.match(source, /address-history-toggle/);
  assert.match(source, /address-history-chevron/);
  assert.doesNotMatch(source, />⌄<\/button>/);
  assert.match(source, /aria-expanded/);
  assert.match(source, /address-history-menu/);
  assert.match(source, /address-history-option/);
  assert.doesNotMatch(source, /address-history-select/);
  assert.match(source, /document\.addEventListener\("pointerdown"/);
  assert.match(source, /closest\("\.address-input-shell"\)/);
  assert.match(source, /forwardingAddressHistory/);
  assert.match(source, /forwardingAddressHistoryForTarget/);
  assert.match(source, /historyKey/);
  assert.match(styleSource, /\.address-history-toggle[^\{]*\{[^}]*display:\s*flex/);
  assert.match(styleSource, /\.address-history-toggle[^\{]*\{[^}]*align-items:\s*center/);
  assert.match(styleSource, /\.address-history-toggle[^\{]*\{[^}]*justify-content:\s*center/);
  assert.match(styleSource, /\.address-history-chevron[^\{]*\{[^}]*transform:/);
});
