import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { targetFromDraft, normalizeTargetBasePath } from "../../src/renderer/components/ConfigPages";
import { getAppConfigValidationError } from "../../src/shared/validation";
import { ConfigStore } from "../../src/core/config/config-store";

test("does not emit an empty base path for root addresses", () => {
  assert.equal(normalizeTargetBasePath("/"), undefined);
  assert.equal(normalizeTargetBasePath("//"), undefined);
});

test("keeps a real target base path after trimming trailing slashes", () => {
  assert.equal(normalizeTargetBasePath("/ant///"), "/ant");
});

test("produces a saveable target for a root address", () => {
  const target = targetFromDraft({ id: "hq", name: "hq", address: "http://127.0.0.1:7778/", enabled: true }, 0);
  assert.equal(target.basePath, undefined);
  assert.equal(getAppConfigValidationError({
    server: { bindHost: "127.0.0.1", port: 8080, timeoutMs: 30000, loggingEnabled: true },
    httpRules: [],
    tcpTargets: [target],
    localValues: {},
    mapValues: {},
    accounts: {},
    cache: { rootDir: "", downloadTarget: "", decryptEnabled: false, autoDownload: false },
  }), undefined);
});

test("saves and reloads the forwarding target generated by the address form", async () => {
  const directory = await mkdtemp(path.join(os.tmpdir(), "local-forwarder-address-save-"));
  const target = targetFromDraft({ id: "hq", name: "hq", address: "http://127.0.0.1:7778//", enabled: true }, 0);
  const config = {
    server: { bindHost: "127.0.0.1", port: 8080, timeoutMs: 30000, loggingEnabled: true },
    httpRules: [],
    tcpTargets: [target],
    localValues: {},
    mapValues: {},
    accounts: {},
    cache: { rootDir: "", downloadTarget: "", decryptEnabled: false, autoDownload: false },
  };
  try {
    const store = new ConfigStore(path.join(directory, "internal.json"));
    await store.save(config);
    const restored = await store.load();
    assert.deepEqual(restored.tcpTargets, [target]);
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
});
