import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { targetFromDraft, normalizeTargetBasePath, addressForTarget } from "../../src/renderer/components/ConfigPages";
import { getAppConfigValidationError } from "../../src/shared/validation";
import { ConfigStore } from "../../src/core/config/config-store";

test("does not emit an empty base path for root addresses", () => {
  assert.equal(normalizeTargetBasePath("/"), undefined);
  assert.equal(normalizeTargetBasePath("//"), undefined);
});

test("keeps a real target base path after trimming trailing slashes", () => {
  assert.equal(normalizeTargetBasePath("/ant///"), "/ant");
});

test("produces a saveable target for a root address", () => {
  const target = targetFromDraft({ id: "hq", name: "hq", address: "http://127.0.0.1:7778/", enabled: true }, 0);
  assert.equal(target.basePath, undefined);
  assert.equal(getAppConfigValidationError({
    server: { bindHost: "127.0.0.1", port: 8080, timeoutMs: 30000, loggingEnabled: true },
    httpRules: [],
    tcpTargets: [target],
    localValues: {},
    mapValues: {},
    accounts: {},
    cache: { rootDir: "", downloadTarget: "", decryptEnabled: false, autoDownload: false },
  }), undefined);
});

test("defaults a bare legacy-style reqxml address to TCP", () => {
  const target = targetFromDraft({ id: "jy", name: "jy", address: "123.103.83.82:6110", enabled: true }, 1);
  assert.equal(target.protocol, undefined);
  assert.equal(target.transport, undefined);
});

test("does not display a TCP target as HTTP when legacy protocol metadata is present", () => {
  assert.equal(addressForTarget({ id: "jy", name: "jy", host: "123.103.83.82", port: 6064, protocol: "http", enabled: true }), "tcp://123.103.83.82:6064");
  assert.equal(addressForTarget({ id: "jy", name: "jy", host: "123.103.83.82", port: 6064, protocol: "http", transport: "http", enabled: true }), "http://123.103.83.82:6064");
});

test("saves and reloads the forwarding target generated by the address form", async () => {
  const directory = await mkdtemp(path.join(os.tmpdir(), "local-forwarder-address-save-"));
  const target = targetFromDraft({ id: "hq", name: "hq", address: "http://127.0.0.1:7778//", enabled: true }, 0);
  const config = {
    server: { bindHost: "127.0.0.1", port: 8080, timeoutMs: 30000, loggingEnabled: true },
    httpRules: [],
    tcpTargets: [target],
    localValues: {},
    mapValues: {},
    accounts: {},
    cache: { rootDir: "", downloadTarget: "", decryptEnabled: false, autoDownload: false },
  };
  try {
    const store = new ConfigStore(path.join(directory, "internal.json"));
    await store.save(config);
    const restored = await store.load();
    assert.deepEqual(restored.tcpTargets, [target]);
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
});

test("address fields auto-save on blur without the explanatory text or save button", async () => {
  const source = await readFile("src/renderer/components/ConfigPages.tsx", "utf8");
  assert.doesNotMatch(source, /按 hq、jy、zx 顺序配置旧版 Node 转发地址/);
  assert.doesNotMatch(source, /保存转发地址/);
  assert.match(source, /saveAddressDrafts/);
  assert.match(source, /onBlur=\{\(\) => void saveAddressDrafts\(\)\}/);
});
